# Development
development:
  adapter: postgresql
  database: sana_coding_interview_development
  username: application
  password: root
  host: localhost
  port: 5432

# Production
production:
  adapter: postgresql
  database: sana_coding_interview
  username: application
  password: 212134
  host: localhost
  port: 5432

# Staging
staging:
  adapter: postgresql
  database: sana_coding_interview_staging
  username: sana_coding_interview_staging
  password: 212134
  host: localhost
  port: 5432



